version: '3'
services:
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    volumes:
      - ./dist:/app
