version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    volumes:
      - .:/app
